{% set name = "backoff" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 407f1bc0f22723648a8880821b935ce5df8475cf04f7b6b5017ae264d30f6069

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - python >=3.7

test:
  imports:
    - backoff
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/litl/backoff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Function decoration for backoff and retry
  description: |
    This module provides function decorators which can be used to wrap a function such that it will be retried until
    some condition is met. It is meant to be of use when accessing unreliable resources with the potential for
    intermittent failures i.e. network resources and external APIs. Somewhat more generally, it may also be of use for
    dynamically polling resources for externally generated content.
  dev_url: https://github.com/litl/backoff

extra:
  recipe-maintainers:
    - gatesn
    - bgreen-litl
    - synapticarbors
